name: Ubuntu SSH Server

on:
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    env:
      SSH_USER: ubuntu
      SSH_PASS: ${{ secrets.SSH_PASSWORD }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${TAILSCALE_AUTH_KEY} --hostname=gh-ubuntu-${{ github.run_id }}

      - name: Show Tailscale IP
        run: |
          echo "✅ Tailscale IP Address:"
          tailscale ip -4

      - name: Create SSH User and Start SSH Server
        run: |
          sudo adduser --disabled-password --gecos "" ${SSH_USER}
          echo "${SSH_USER}:${SSH_PASS}" | sudo chpasswd
          sudo usermod -aG sudo ${SSH_USER}
          
          sudo apt-get update -y
          sudo apt-get install -y openssh-server

          # Password login enable
          sudo sed -i 's/^#PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config

          sudo systemctl enable ssh
          sudo systemctl restart ssh

          echo "✅ SSH User: ${SSH_USER}"
          echo "✅ SSH Password: Set via GitHub Secrets"
          echo "✅ Tailscale IP Address:"
          tailscale ip -4

      - name: Keep Runner Alive
        run: |
          echo "Server is running... Keep this window open."
          while true; do
            echo "[$(date)] Ubuntu server still active..."
            sleep 300
          done
