name: Ubuntu SSH Server

on:
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ubuntu-${{ github.run_id }}

      - name: Show Tailscale IP
        run: |
          echo "✅ Tailscale IP Address:"
          tailscale ip -4

      - name: Create SSH User
        run: |
          # အသုံးပြုသူအသစ်ဖန်တီး
          sudo useradd -m ubuntu
          echo 'ubuntu:Pass1234!' | sudo chpasswd
          
          # sudo အသုံးပြုခွင့်ပေး
          sudo usermod -aG sudo ubuntu

          # SSH server install
          sudo apt-get update -y
          sudo apt-get install -y openssh-server

          # SSH service enable
          sudo systemctl enable ssh
          sudo systemctl restart ssh

          echo "✅ SSH User: ubuntu"
          echo "✅ SSH Password: Pass1234!"
          echo "============================"
          tailscale ip -4

      - name: Keep Runner Alive
        run: |
          echo "Server is running... Keep window open."
          while true; do
            echo "[$(date)] Ubuntu server still active..."
            sleep 300
          done
